INSERT INTO `UserAdmin`.`USER` (`ID`, `LASTNAME`, `STATUS`, `DEFAULTLANGUAGE`, `PASSWORD`, `VERSION`, `EMAILID`, `TITLE`, `USERNAME`, `FIRSTNAME`) VALUES ('1', 'Patil', 'ACTIVE', 'ENGLISH', 'XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=', 1, 'root@pandurangpatil.com', 'Mr.', 'root', 'Pandurang');
INSERT INTO `UserAdmin`.`APPLICATION` (`ID`, `BUSINESSNAME`, `STATUS`, `UPDATEDBY`, `VERSION`, `CREATEDON`, `CREATEDBY`, `MULTIPLECONTEXTS`, `DOMAIN`, `URL`, `ICONURL`, `DEFAULTSTATUS`, `UPDATEON`, `OWNER_ID`) VALUES ('1', '3a4users', 'ACTIVE', '1', 1, CURDATE(), '1', 0, 'admin.agnie.co.in', '/userapp/landing.jsp', '/userapp/images/agnie_logo150x100.png', 'ACTIVE'  , CURDATE(), '1');
/* Application level permissions */
INSERT INTO `UserAdmin`.`PERMISSION` (`ID`, `CREATEDON`, `LEVEL`, `CREATEDBY`, `NAME`, `CODE`, `VERSION`, `UPDATEON`, `UPDATEDBY`,`APPLICATION_ID`) VALUES ('1', CURDATE(), 'APPLICATION', '1', 'Create User', 'perm_user_create', 1, CURDATE(), '1', '1');
INSERT INTO `UserAdmin`.`PERMISSION` (`ID`, `CREATEDON`, `LEVEL`, `CREATEDBY`, `NAME`, `CODE`, `VERSION`, `UPDATEON`, `UPDATEDBY`,`APPLICATION_ID`) VALUES ('2', CURDATE(), 'APPLICATION', '1', 'View user details', 'perm_user_view', 1, CURDATE(), '1', '1');
INSERT INTO `UserAdmin`.`PERMISSION` (`ID`, `CREATEDON`, `LEVEL`, `CREATEDBY`, `NAME`, `CODE`, `VERSION`, `UPDATEON`, `UPDATEDBY`,`APPLICATION_ID`) VALUES ('3', CURDATE(), 'APPLICATION', '1', 'Delete user details', 'perm_user_delete', 1, CURDATE(), '1', '1');
INSERT INTO `UserAdmin`.`PERMISSION` (`ID`, `CREATEDON`, `LEVEL`, `CREATEDBY`, `NAME`, `CODE`, `VERSION`, `UPDATEON`, `UPDATEDBY`,`APPLICATION_ID`) VALUES ('4', CURDATE(), 'APPLICATION', '1', 'Edit general user details', 'perm_user_edit_general', 1, CURDATE(), '1', '1');
INSERT INTO `UserAdmin`.`PERMISSION` (`ID`, `CREATEDON`, `LEVEL`, `CREATEDBY`, `NAME`, `CODE`, `VERSION`, `UPDATEON`, `UPDATEDBY`,`APPLICATION_ID`) VALUES ('5', CURDATE(), 'APPLICATION', '1', 'Reset user password', 'perm_user_edit_resetpwd', 1, CURDATE(), '1', '1');
INSERT INTO `UserAdmin`.`PERMISSION` (`ID`, `CREATEDON`, `LEVEL`, `CREATEDBY`, `NAME`, `CODE`, `VERSION`, `UPDATEON`, `UPDATEDBY`,`APPLICATION_ID`) VALUES ('6', CURDATE(), 'APPLICATION', '1', 'Create application', 'perm_app_create', 1, CURDATE(), '1', '1');

/* Application level admin permissions */
INSERT INTO `UserAdmin`.`PERMISSION` (`ID`, `CREATEDON`, `LEVEL`, `CREATEDBY`, `NAME`, `CODE`, `VERSION`, `UPDATEON`, `UPDATEDBY`,`APPLICATION_ID`) VALUES ('7', CURDATE(), 'ADMIN_APP', '1', 'Delete application', 'perm_app_delete', 1, CURDATE(), '1', '1');
INSERT INTO `UserAdmin`.`PERMISSION` (`ID`, `CREATEDON`, `LEVEL`, `CREATEDBY`, `NAME`, `CODE`, `VERSION`, `UPDATEON`, `UPDATEDBY`,`APPLICATION_ID`) VALUES ('8', CURDATE(), 'ADMIN_APP', '1', 'Edit application details', 'perm_app_edit_setting_edit', 1, CURDATE(), '1', '1');
INSERT INTO `UserAdmin`.`PERMISSION` (`ID`, `CREATEDON`, `LEVEL`, `CREATEDBY`, `NAME`, `CODE`, `VERSION`, `UPDATEON`, `UPDATEDBY`,`APPLICATION_ID`) VALUES ('9', CURDATE(), 'ADMIN_APP', '1', 'View application deails', 'perm_app_edit_setting_view', 1, CURDATE(), '1', '1');
INSERT INTO `UserAdmin`.`PERMISSION` (`ID`, `CREATEDON`, `LEVEL`, `CREATEDBY`, `NAME`, `CODE`, `VERSION`, `UPDATEON`, `UPDATEDBY`,`APPLICATION_ID`) VALUES ('10', CURDATE(), 'ADMIN_APP', '1', 'Create Role', 'perm_app_edit_role_create', 1, CURDATE(), '1', '1');
INSERT INTO `UserAdmin`.`PERMISSION` (`ID`, `CREATEDON`, `LEVEL`, `CREATEDBY`, `NAME`, `CODE`, `VERSION`, `UPDATEON`, `UPDATEDBY`,`APPLICATION_ID`) VALUES ('11', CURDATE(), 'ADMIN_APP', '1', 'Edit Role', 'perm_app_edit_role_edit', 1, CURDATE(), '1', '1');
INSERT INTO `UserAdmin`.`PERMISSION` (`ID`, `CREATEDON`, `LEVEL`, `CREATEDBY`, `NAME`, `CODE`, `VERSION`, `UPDATEON`, `UPDATEDBY`,`APPLICATION_ID`) VALUES ('12', CURDATE(), 'ADMIN_APP', '1', 'View Role', 'perm_app_edit_role_view', 1, CURDATE(), '1', '1');
INSERT INTO `UserAdmin`.`PERMISSION` (`ID`, `CREATEDON`, `LEVEL`, `CREATEDBY`, `NAME`, `CODE`, `VERSION`, `UPDATEON`, `UPDATEDBY`,`APPLICATION_ID`) VALUES ('13', CURDATE(), 'ADMIN_APP', '1', 'Delete Role', 'perm_app_edit_role_delete', 1, CURDATE(), '1', '1');
INSERT INTO `UserAdmin`.`PERMISSION` (`ID`, `CREATEDON`, `LEVEL`, `CREATEDBY`, `NAME`, `CODE`, `VERSION`, `UPDATEON`, `UPDATEDBY`,`APPLICATION_ID`) VALUES ('14', CURDATE(), 'ADMIN_APP', '1', 'Create Permission', 'perm_app_edit_permission_create', 1, CURDATE(), '1', '1');
INSERT INTO `UserAdmin`.`PERMISSION` (`ID`, `CREATEDON`, `LEVEL`, `CREATEDBY`, `NAME`, `CODE`, `VERSION`, `UPDATEON`, `UPDATEDBY`,`APPLICATION_ID`) VALUES ('15', CURDATE(), 'ADMIN_APP', '1', 'Edit Permission', 'perm_app_edit_permission_edit', 1, CURDATE(), '1', '1');
INSERT INTO `UserAdmin`.`PERMISSION` (`ID`, `CREATEDON`, `LEVEL`, `CREATEDBY`, `NAME`, `CODE`, `VERSION`, `UPDATEON`, `UPDATEDBY`,`APPLICATION_ID`) VALUES ('16', CURDATE(), 'ADMIN_APP', '1', 'View Permission', 'perm_app_edit_permission_view', 1, CURDATE(), '1', '1');
INSERT INTO `UserAdmin`.`PERMISSION` (`ID`, `CREATEDON`, `LEVEL`, `CREATEDBY`, `NAME`, `CODE`, `VERSION`, `UPDATEON`, `UPDATEDBY`,`APPLICATION_ID`) VALUES ('17', CURDATE(), 'ADMIN_APP', '1', 'Delete Permission', 'perm_app_edit_permission_delete', 1, CURDATE(), '1', '1');
INSERT INTO `UserAdmin`.`PERMISSION` (`ID`, `CREATEDON`, `LEVEL`, `CREATEDBY`, `NAME`, `CODE`, `VERSION`, `UPDATEON`, `UPDATEDBY`,`APPLICATION_ID`) VALUES ('18', CURDATE(), 'ADMIN_APP', '1', 'Create Context', 'perm_app_edit_ctxt_create', 1, CURDATE(), '1', '1');
INSERT INTO `UserAdmin`.`PERMISSION` (`ID`, `CREATEDON`, `LEVEL`, `CREATEDBY`, `NAME`, `CODE`, `VERSION`, `UPDATEON`, `UPDATEDBY`,`APPLICATION_ID`) VALUES ('19', CURDATE(), 'ADMIN_APP', '1', 'Manage User registration', 'perm_app_edit_user_reg', 1, CURDATE(), '1', '1');
INSERT INTO `UserAdmin`.`PERMISSION` (`ID`, `CREATEDON`, `LEVEL`, `CREATEDBY`, `NAME`, `CODE`, `VERSION`, `UPDATEON`, `UPDATEDBY`,`APPLICATION_ID`) VALUES ('20', CURDATE(), 'ADMIN_APP', '1', 'Manage User de registration', 'perm_app_edit_user_dereg', 1, CURDATE(), '1', '1');
INSERT INTO `UserAdmin`.`PERMISSION` (`ID`, `CREATEDON`, `LEVEL`, `CREATEDBY`, `NAME`, `CODE`, `VERSION`, `UPDATEON`, `UPDATEDBY`,`APPLICATION_ID`) VALUES ('21', CURDATE(), 'ADMIN_APP', '1', 'Mange user\'s application Roles', 'perm_app_edit_user_rolemgmt', 1, CURDATE(), '1', '1');
INSERT INTO `UserAdmin`.`PERMISSION` (`ID`, `CREATEDON`, `LEVEL`, `CREATEDBY`, `NAME`, `CODE`, `VERSION`, `UPDATEON`, `UPDATEDBY`,`APPLICATION_ID`) VALUES ('22', CURDATE(), 'ADMIN_APP', '1', 'Mange user\'s admin Roles', 'perm_app_edit_user_admin_edit_rolemgmt', 1, CURDATE(), '1', '1');
INSERT INTO `UserAdmin`.`PERMISSION` (`ID`, `CREATEDON`, `LEVEL`, `CREATEDBY`, `NAME`, `CODE`, `VERSION`, `UPDATEON`, `UPDATEDBY`,`APPLICATION_ID`) VALUES ('23', CURDATE(), 'ADMIN_APP', '1', 'List contexts', 'perm_app_edit_ctxt_list', 1, CURDATE(), '1', '1');

/* Context level admin permissions */
INSERT INTO `UserAdmin`.`PERMISSION` (`ID`, `CREATEDON`, `LEVEL`, `CREATEDBY`, `NAME`, `CODE`, `VERSION`, `UPDATEON`, `UPDATEDBY`,`APPLICATION_ID`) VALUES ('24', CURDATE(), 'ADMIN_CTX', '1', 'View contexts details', 'perm_app_edit_ctxt_view', 1, CURDATE(), '1', '1');
INSERT INTO `UserAdmin`.`PERMISSION` (`ID`, `CREATEDON`, `LEVEL`, `CREATEDBY`, `NAME`, `CODE`, `VERSION`, `UPDATEON`, `UPDATEDBY`,`APPLICATION_ID`) VALUES ('25', CURDATE(), 'ADMIN_CTX', '1', 'Edit contexts', 'perm_app_edit_ctxt_edit', 1, CURDATE(), '1', '1');
INSERT INTO `UserAdmin`.`PERMISSION` (`ID`, `CREATEDON`, `LEVEL`, `CREATEDBY`, `NAME`, `CODE`, `VERSION`, `UPDATEON`, `UPDATEDBY`,`APPLICATION_ID`) VALUES ('26', CURDATE(), 'ADMIN_CTX', '1', 'Delete Contexts', 'perm_app_edit_ctxt_delete', 1, CURDATE(), '1', '1');
INSERT INTO `UserAdmin`.`PERMISSION` (`ID`, `CREATEDON`, `LEVEL`, `CREATEDBY`, `NAME`, `CODE`, `VERSION`, `UPDATEON`, `UPDATEDBY`,`APPLICATION_ID`) VALUES ('27', CURDATE(), 'ADMIN_CTX', '1', 'Manage user context registration', 'perm_app_edit_ctxt_edit_user_reg', 1, CURDATE(), '1', '1');
INSERT INTO `UserAdmin`.`PERMISSION` (`ID`, `CREATEDON`, `LEVEL`, `CREATEDBY`, `NAME`, `CODE`, `VERSION`, `UPDATEON`, `UPDATEDBY`,`APPLICATION_ID`) VALUES ('28', CURDATE(), 'ADMIN_CTX', '1', 'Manage user context de registration', 'perm_app_edit_ctxt_edit_user_dereg', 1, CURDATE(), '1', '1');
INSERT INTO `UserAdmin`.`PERMISSION` (`ID`, `CREATEDON`, `LEVEL`, `CREATEDBY`, `NAME`, `CODE`, `VERSION`, `UPDATEON`, `UPDATEDBY`,`APPLICATION_ID`) VALUES ('29', CURDATE(), 'ADMIN_CTX', '1', 'Manage user\'s context roles', 'perm_app_edit_ctxt_edit_user_rolemgmt', 1, CURDATE(), '1', '1');
INSERT INTO `UserAdmin`.`PERMISSION` (`ID`, `CREATEDON`, `LEVEL`, `CREATEDBY`, `NAME`, `CODE`, `VERSION`, `UPDATEON`, `UPDATEDBY`,`APPLICATION_ID`) VALUES ('30', CURDATE(), 'ADMIN_CTX', '1', 'Manage user\'s context admin roles', 'perm_app_edit_ctxt_edit_user_admin_edit_rolemgmt', 1, CURDATE(), '1', '1');